@leaders =
  [
    name: 'Bill O’Reilly'
    birth: '* 1949'
    title: 'Politisk kommentator, Fox News, USA'
    quote: 'Sen homoäktenskap blev lagligt i Sverige, har äktenskapet som institution kollapsat.'
    source: 'The O’Reilly Factor, tv-program, 2005-06-01 (det vill säga innan samkönat äktenskap blev lagligt), fritt översatt'
    more: 'https://www.youtube.com/watch?v=jo8K4YPi-v0'
    img: 'images/leaders/pippi.png'
  ,
    name: 'Herman Lundborg'
    birth: '* 1868   † 1943'
    title: 'Chef för Rasbiologiska institutet, Sverige'
    quote: 'Godhjärtade män och kvinnor hjälpa icke sällan urskillningslöst fram fysiskt och psykiskt svagt utrustade personer, som sedan fortplanta sig och ge sina mindervärdiga anlag i arv åt nya släkten, vilka i sin tur falla samhället till last.'
    source: 'Degenerationsfaran, bok, 1922'
    more: 'http://fof.se/tidning/2012/8/en-meningslos-sortering-av-manniskor'
    img: 'images/leaders/pippi.png'
  ,
    name: 'Åke Green'
    birth: '* 1937'
    title: 'Pingstpastor, Sverige'
    quote: 'Sexuella abnormiteter är en djup cancersvulst på hela samhällskroppen.'
    source: 'Predikan om homosexualitet i Borgholms församling, 2003-07-20'
    more: 'http://sv.wikipedia.org/wiki/%C3%85ke_Green'
    img: 'images/leaders/pippi.png'
  ,
    name: 'Gabriele Kuby'
    birth: '* 1944'
    title: 'Sociolog, Tyskland'
    quote: 'Vart tredje svenskt barn är psykiskt stört på grund av dagisvistelse.'
    source: 'Tv-debatt i tysk tv, 2007-02-27, översättning av tidningen Metro'
    more: 'http://www.metro.se/nyheter/svenska-barn-slagpase-i-tysk-dagisdebatt/Objgbz!22_4617-45/'
    img: 'images/leaders/pippi.png'
  ,
    name: 'Yelena Isinbayeva'
    birth: '* 1982'
    title: 'Stavhoppare, Ryssland'
    quote: 'Det kommer från vår historia. Vi har aldrig haft några sådana här problem i Ryssland och vi vill inte ha det i framtiden'
    source: 'Om Rysslands syn på homosexuella vid presskonferens i samband med friidrotts-VM, 2013-08-05, fritt översatt'
    more: 'http://www.telegraph.co.uk/sport/othersports/athletics/10245582/World-champion-Yelena-Isinbayeva-criticises-Swedish-athletes-for-supporting-gay-rights.html'
    img: 'images/leaders/pippi.png'
  ,
    name: 'Arne Hegerfors'
    birth: '* 1942'
    title: 'Journalist och sportkommentator, Sverige'
    quote: 'Det ser mörkt ut på Kameruns avbytarbänk.'
    source: 'Kommentar efter att England fått sin andra straff i matchen mot Kamerun i fotbolls-VM 1990, 1990-07-01'
    more: 'https://www.youtube.com/watch?v=mb1fYInj7vc'
    img: 'images/leaders/pippi.png'
  ,
    name: 'Pippi Långstrump'
    birth: '* 1945'
    title: 'Fiktiv karaktär, Sverige'
    quote: 'Lever vi inte i ett fritt land kanske? Får man inte gå hur man vill?'
    source: 'Från boken Pippi Långstrum av Astrid Lindgren, 1945'
    more: 'http://www.astridlindgren.se/mer-fakta/citat/pippi'
    img: 'images/leaders/pippi.png'
  ,
    name: 'Harvey Milk'
    birth: '* 1930   † 1978'
    title: 'Politiker och förkämpe för homosexuellas rättigheter, USA'
    quote: 'Det behövs inga kompromisser för att skänka folk sina rättigheter … respekt för individen kostar inte pengar. Det behövs ingen politisk uppgörelse för att skänka människor sin frihet. Det behövs ingen utredning för att stoppa förtrycket.'
    source: 'Okänd originalkälla, hämtat från GoodReads, fritt översatt'
    more: 'http://www.goodreads.com/quotes/223676-it-takes-no-compromise-to-give-people-their-rights-it-takes'
    img: 'images/leaders/pippi.png'
  ,
    name: 'Martin Luther King Jr'
    birth: '* 1929   † 1968'
    title: 'Pastor och ledare i människorättsrörelsen, USA'
    quote: 'Mörker kan inte fördriva mörker: bara ljus kan göra det. Hat kan inte fördriva hat: bara kärlek kan göra det.'
    source: 'Från boken A Testament of Hope: The Essential Writings and Speeches, 2003, fritt översatt'
    more: 'http://www.goodreads.com/quotes/943-darkness-cannot-drive-out-darkness-only-light-can-do-that'
    img: 'images/leaders/pippi.png'
  ,
    name: 'Nelson Mandela'
    birth: '* 1918   † 2013'
    title: 'Advokat, frihetskämpe och politiker, Sydafrika'
    quote: 'Jag gillar vänner som kan tänka självständigt för dom tenderar hjälpa dig att se problem från alla perspektiv.'
    source: 'Okänd originalkälla, hämtat från USA Today, fritt översatt'
    more: 'http://www.usatoday.com/story/news/nation-now/2013/12/05/nelson-mandela-quotes/3775255/'
    img: 'images/leaders/pippi.png'
  ]